name = "server"
compatibility_date = "2023-12-01"
main = "src/index.ts"

routes = [{ pattern = "YOUR_PUBLIC_DOMAIN", custom_domain = true }]

[[d1_databases]]
binding = "DB" 
database_name = "YOUR_DATABASE_NAME"
database_id = "YOUR_DATABASE_ID"

[[r2_buckets]]
binding = "R2"
bucket_name = "YOUR_R2_BUCKET_NAME"

[[unsafe.bindings]]
name = "API_LIMITER_ONCE"
type = "ratelimit"
# An identifier you define, that is unique to your Cloudflare account.
# Must be an integer.
namespace_id = "1001"
# Period: the duration of the period, in seconds. Must be either 10 or 60
simple = { limit = 1, period = 60 }

[[unsafe.bindings]]
name = "API_LIMITER_LARGE"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 180, period = 60 }

[[unsafe.bindings]]
name = "API_LIMITER_REGULAR"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 30, period = 60 }

[[unsafe.bindings]]
name = "API_LIMITER_SMALL"
type = "ratelimit"
namespace_id = "1003"
simple = { limit = 10, period = 60 }

[[unsafe.bindings]]
name = "API_LIMITER_TINY"
type = "ratelimit"
namespace_id = "1003"
simple = { limit = 5, period = 60 }


[vars]
MAIN_DOMAIN = "https://YOUR_PUBLIC_DOMAIN"
WEBFLOW_DOMAIN = "https://YOUR_WEBFLOW_DOMAIN"
LOGIN_ROUTE = "/auth/login"
SUCESSFUL_LOGIN_REDIRECT = "/app/home"
EMAIL_VERIFICATION_ROUTE = "/auth/verify-email"
SECURED_ROUTES = "app,dashboard"
SETTINGS_ROUTE = "/app/settings"
SUCESSFUL_PAYMENT_REDIRECT = "/app/payment"
RESET_PASSWORD_ROUTE = "/auth/reset-password"
JS_SCRIPT_DOMAIN = "https://YOUR_FRONTEND-JS-PUBLIC_DOMAIN"

